### ISSUE TITLE
After entering right Recipient ID

### ISSUE THREAD

**Issue by HeinrichPet** [International-Data-Spaces-Association/IDS-ConfigurationManager-UI#55]
Hi,

Setup:
-    DSC branch 386 on port 8080
-    UI branch DSC on port 8082 connected to 8080 backend
-    DSC branch 386 on port 8081
-    Input on Recipient ID: https://localhost:8081/

After entering the right Recipient ID i get a list with one element:
![grafik](https://user-images.githubusercontent.com/59964830/125847888-54653ad3-76af-4935-a84b-9a2ff8ef9c38.png)

I can click on the eye and get an empty metadata pop up (Title, Decsription, License, Language, etc.).

Logs UI:
```
[1] >>> POST https://localhost:8080/api/ids/description?recipient=https%3A%2F%2Flocalhost%3A8081%2Fapi%2Fids%2Fdata
[1] >>> DATA:  undefined
[1] >>> POST https://localhost:8080/api/ids/description?recipient=https%3A%2F%2Flocalhost%3A8081%2Fapi%2Fids%2Fdata&elementId=https%3A%2F%2Flocalhost%3A8081%2Fapi%2Fcatalogs%2Fd386994b-d80a-4f53-be45-f9ddb33c5e0e
[1] >>> DATA:  undefined
[1] >>> POST https://localhost:8080/api/ids/description?recipient=https%3A%2F%2Flocalhost%3A8081%2Fapi%2Fids%2Fdata
[1] >>> DATA:  undefined
[1] >>> POST https://localhost:8080/api/ids/description?recipient=https%3A%2F%2Flocalhost%3A8081%2Fapi%2Fids%2Fdata&elementId=https%3A%2F%2Flocalhost%3A8081%2Fapi%2Fcatalogs%2Fd386994b-d80a-4f53-be45-f9ddb33c5e0e
[1] >>> DATA:  undefined
[1] >>> POST https://localhost:8080/api/ids/description?recipient=https%3A%2F%2Flocalhost%3A8081%2Fapi%2Fids%2Fdata
[1] >>> DATA:  undefined
[1] >>> POST https://localhost:8080/api/ids/description?recipient=https%3A%2F%2Flocalhost%3A8081%2Fapi%2Fids%2Fdata&elementId=https%3A%2F%2Flocalhost%3A8081%2Fapi%2Fcatalogs%2Fd386994b-d80a-4f53-be45-f9ddb33c5e0e
[1] >>> DATA:  undefined
[1] >>> POST https://localhost:8080/api/ids/description?recipient=https%3A%2F%2Flocalhost%3A8081%2Fapi%2Fids%2Fdata
[1] >>> DATA:  undefined
[1] >>> POST https://localhost:8080/api/ids/description?recipient=https%3A%2F%2Flocalhost%3A8081%2Fapi%2Fids%2Fdata&elementId=https%3A%2F%2Flocalhost%3A8081%2Fapi%2Fcatalogs%2Fd386994b-d80a-4f53-be45-f9ddb33c5e0e
[1] >>> DATA:  undefined
[1] >>> POST https://localhost:8080/api/ids/description?recipient=https%3A%2F%2Flocalhost%3A8081%2Fapi%2Fids%2Fdata
[1] >>> DATA:  undefined
```

Logs DSC:
```
[only the same JWT error each time]
2021-07-15T21:39:44,883 [https-jsse-nio-8080-exec-1] WARN - Could not parse jwt!
2021-07-15T21:39:44,883 [https-jsse-nio-8080-exec-1] WARN - [DAPS Token Manager Service] Mandatorily required information of the connector certificate is missing (AKI/SKI)!
2021-07-15T21:39:44,883 [https-jsse-nio-8080-exec-1] WARN - [DAPS Token Manager Service] Since the connector is in TEST_DEPLOYMENT the IDS-Message is now sent without a valid DAT.
2021-07-15T21:39:44,884 [https-jsse-nio-8080-exec-1] WARN - [DAPS Token Manager Service] If the connector is switched to PRODUCTIVE_DEPLOYMENT, no message without valid DAT will be sent at this point anymore!
2021-07-15T21:39:44,946 [https-jsse-nio-8080-exec-1] ERROR - JWT strings must contain exactly 2 period characters. Found: 0
io.jsonwebtoken.MalformedJwtException: JWT strings must contain exactly 2 period characters. Found: 0
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:235) ~[jjwt-0.9.1.jar!/:0.9.1]
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:481) ~[jjwt-0.9.1.jar!/:0.9.1]
        at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:541) ~[jjwt-0.9.1.jar!/:0.9.1]
        at de.fraunhofer.ids.messaging.core.daps.DapsValidator.getClaims(DapsValidator.java:60) [core-4.1.1.4.jar!/:?]
        at de.fraunhofer.ids.messaging.core.daps.TokenProviderService.isExpired(TokenProviderService.java:164) [core-4.1.1.4.jar!/:?]
        at de.fraunhofer.ids.messaging.core.daps.TokenProviderService.provideDapsToken(TokenProviderService.java:81) [core-4.1.1.4.jar!/:?]
        at de.fraunhofer.ids.messaging.core.daps.TokenProviderService.getDAT(TokenProviderService.java:69) [core-4.1.1.4.jar!/:?]
        at io.dataspaceconnector.service.ids.ConnectorService.getCurrentDat(ConnectorService.java:125) [classes!/:6.0.0]
        at io.dataspaceconnector.service.ids.ConnectorService$$FastClassBySpringCGLIB$$c9902bac.invoke(<generated>) [classes!/:6.0.0]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.3.8.jar!/:5.3.8]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) [spring-aop-5.3.8.jar!/:5.3.8]
        at io.dataspaceconnector.service.ids.ConnectorService$$EnhancerBySpringCGLIB$$249543b.getCurrentDat(<generated>) [classes!/:6.0.0]
        at io.dataspaceconnector.service.message.type.DescriptionRequestService.buildMessage(DescriptionRequestService.java:54) [classes!/:6.0.0]
        at io.dataspaceconnector.service.message.type.DescriptionRequestService.buildMessage(DescriptionRequestService.java:38) [classes!/:6.0.0]
        at io.dataspaceconnector.service.message.type.AbstractMessageService.send(AbstractMessageService.java:100) [classes!/:6.0.0]
        at io.dataspaceconnector.service.message.type.DescriptionRequestService.sendMessage(DescriptionRequestService.java:85) [classes!/:6.0.0]
        at io.dataspaceconnector.controller.message.DescriptionRequestMessageController.sendMessage(DescriptionRequestMessageController.java:86) [classes!/:6.0.0]
        at io.dataspaceconnector.controller.message.DescriptionRequestMessageController$$FastClassBySpringCGLIB$$3a8dce0c.invoke(<generated>) [classes!/:6.0.0]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.3.8.jar!/:5.3.8]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) [spring-aop-5.3.8.jar!/:5.3.8]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.3.8.jar!/:5.3.8]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) [spring-aop-5.3.8.jar!/:5.3.8]
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:61) [spring-security-core-5.5.1.jar!/:5.5.1]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.3.8.jar!/:5.3.8]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) [spring-aop-5.3.8.jar!/:5.3.8]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) [spring-aop-5.3.8.jar!/:5.3.8]
        at io.dataspaceconnector.controller.message.DescriptionRequestMessageController$$EnhancerBySpringCGLIB$$6011ef49.sendMessage(<generated>) [classes!/:6.0.0]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) [spring-web-5.3.8.jar!/:5.3.8]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) [spring-web-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) [spring-webmvc-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894) [spring-webmvc-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) [spring-webmvc-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1063) [spring-webmvc-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) [spring-webmvc-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) [spring-webmvc-5.3.8.jar!/:5.3.8]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) [tomcat-embed-core-9.0.48.jar!/:4.0.1]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.3.8.jar!/:5.3.8]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [tomcat-embed-core-9.0.48.jar!/:4.0.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:228) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.48.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:121) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:178) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.8.jar!/:5.3.8]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.8.jar!/:5.3.8]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.8.jar!/:5.3.8]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183) [spring-security-web-5.5.1.jar!/:5.5.1]
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) [spring-web-5.3.8.jar!/:5.3.8]
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) [spring-web-5.3.8.jar!/:5.3.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.3.8.jar!/:5.3.8]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.8.jar!/:5.3.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.3.8.jar!/:5.3.8]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.8.jar!/:5.3.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) [spring-boot-actuator-2.5.2.jar!/:2.5.2]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.8.jar!/:5.3.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.3.8.jar!/:5.3.8]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.8.jar!/:5.3.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) [tomcat-embed-core-9.0.48.jar!/:?]
        at io.opentracing.contrib.web.servlet.filter.TracingFilter.doFilter(TracingFilter.java:189) [opentracing-web-servlet-filter-0.4.0.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723) [tomcat-embed-core-9.0.48.jar!/:?]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.48.jar!/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.48.jar!/:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
2021-07-15T21:39:44,954 [https-jsse-nio-8080-exec-1] WARN - Could not parse jwt!
2021-07-15T21:39:44,954 [https-jsse-nio-8080-exec-1] WARN - [DAPS Token Manager Service] Mandatorily required information of the connector certificate is missing (AKI/SKI)!
2021-07-15T21:39:44,954 [https-jsse-nio-8080-exec-1] WARN - [DAPS Token Manager Service] Since the connector is in TEST_DEPLOYMENT the IDS-Message is now sent without a valid DAT.
2021-07-15T21:39:44,954 [https-jsse-nio-8080-exec-1] WARN - [DAPS Token Manager Service] If the connector is switched to PRODUCTIVE_DEPLOYMENT, no message without valid DAT will be sent at this point anymore!
2021-07-15T21:39:45,015 [https-jsse-nio-8080-exec-1] INFO - URL is valid: https://localhost:8081/api/ids/data
2021-07-15T21:39:45,016 [https-jsse-nio-8080-exec-1] INFO - Ok Http Client Protocols[h2, http/1.1]
2021-07-15T21:39:45,017 [https-jsse-nio-8080-exec-1] INFO - Ok Http Client Protocols[h2, http/1.1]
2021-07-15T21:39:45,017 [https-jsse-nio-8080-exec-1] INFO - Request is HTTPS: true
2021-07-15T21:39:45,446 [https-jsse-nio-8080-exec-1] WARN - Could not deserialize Playload Could not transform input to an appropriate implementing class for de.fraunhofer.iais.eis.Connector
2021-07-15T21:39:45,446 [https-jsse-nio-8080-exec-1] WARN - Skipping Connector-SecurityProfile Attribute!
```
[Log_DSC.txt](https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager-UI/files/6825877/Log_DSC.txt)

Best regards,
Heinrich

**Comment by BastianWel** [comment]
The screenshot show that data (title, publisher, license) is empty which are required fields in the UI.
Did you create this resource with Swagger without setting title, publisher & license?
Then I could reproduce it and make it fault tolerant.

**Comment by BastianWel** [comment]
I was able to get the exact image as in the screenshot by creating a resource in the second DSC with empty metadata and requesting it. The keyword 'DSC' seems to be created automatically in the connector (should be removed?).
The UI displays the data correctly in this case.
